name: GH and Hex.pm Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    uses: TanklesXL/gleam_actions/.github/workflows/release.yaml@5c5d99b6d80e097f6eaf7daffa63bf446ca7d5ea
    secrets:
      HEXPM_USER: ${{ secrets.HEXPM_USER }}
      HEXPM_PASS: ${{ secrets.HEXPM_PASS }}
    with:
      gleam_version: 1.7.0
      erlang_version: 27
      test_erlang: true
      test_node: false
